### ISSUE TITLE
pxn-rectangle component : Unwanted creation of box while moving the image

### ISSUE THREAD

**Issue by bpioge** [pixano/pixano-elements#1]
Quick image moving create unwanted box.

The bug can be reproduced in the bouding-box demo on the pixano website : http://pixano.cea.fr/bounding-box/ with Chrome Version 83.0.4103.61 (Build officiel) (64 bits).
I think this bug affects all pixano elements.
Steps to reproduce : Enable the mode creation by clicking the "Add rectangle" button and then move the image (with the right click) quicky. It creates a small rectangle.

I attach a video of the bug.

[bug-pixano-rectangle.zip](https://github.com/pixano/pixano-elements/files/4805245/bug-pixano-rectangle.zip)

**Comment by camilledupont** [comment]
Hi @bpioge , thank you for your bug report, great catch !
Adding a left-click only condition on shape creation solves the issue. Can you confirm that it works now for you too using the rectangle component ? #0dc7c54d29c5a0acb1251d155907dbb5ccf04b36

**Comment by camilledupont** [comment]
0dc7c54d29c5a0acb1251d155907dbb5ccf04b36

**Comment by bpioge** [comment]
Thank you very much @camilledupont ! It works for me too. I saw your commit and I think you solved another bug that I encoutered (interaction problem after zooming in and out). When do you think it will be released on npm ?

**Comment by camilledupont** [comment]
Great @bpioge ! Let me check that it works well for the other elements, I'll make a release on npm within the week.
Thank you again for the report, and don't hesitate if you encounter another bug/important missing feature :)
