### ISSUE TITLE
onTabulation selection does not reset previously selected shapes display

### ISSUE THREAD

**Issue by bpioge** [pixano/pixano-elements#4]
onTabulation (pxn-canvas-2d.ts) do a this.targetShapes.set([nextShape]). 

In the ShapesEditController, we observe the targetShapes but the "set" does not "clear" the shapes.

https://github.com/pixano/pixano-elements/blob/fbdff55eab94e88df34a18b319a5c8f275a2e2f4/packages/graphics-2d/src/controller.ts#L68

The case "set" should do the action that is in the case "clear" and then, the action in the case "add". We can also (the lazy way) just call this.targetShapes.clear() in onTabulation

**Comment by camilledupont** [comment]
@bpioge thanks so much for this finding :) I just rewrote the set function which clears and set the shapes.
PS: sorry for the delay !
